spring:
  application:
    name: Pop O Bob
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-snowy-silence-ahoq2ovz-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

razorpay:
  key-id: rzp_test_T4aQ5u6TRc7G0O
  key-secret: wds1TgsHLGs5qdrb7NwmAhtN

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
